version: '3.8'

services:
  frontend:
    build: ./timemanager-webapp
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./timemanager-api
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:password@db/timemanager
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=timemanager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
