name: CI/CD

on:
  push:
    branches: [ 17-finishing-cicd ]
  pull_request:
    branches: [ 17-finishing-cicd ]

jobs:
  build-api:
    name: Build and test API
    runs-on: ubuntu-latest
    outputs:
      backend-image: ${{ steps.build-image.outputs.image }}
    steps:
      - uses: actions/checkout@v3

      - name: Liste des fichiers
        run: ls -la

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14"
          otp-version: "25.0"

      - name: Install Dependencies
        working-directory: ./timemanager-api
        run: mix deps.get

      - name: Build Docker Image for API
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: ./timemanager-api
          push: false
          tags: ghcr.io/swangon/timemanager/timemanager-api:latest

  build-webapp:
    name: Build and test Webapp
    runs-on: ubuntu-latest
    outputs:
      frontend-image: ${{ steps.build-image.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        working-directory: ./timemanager-webapp
        run: npm ci

      - name: Build Docker Image for Webapp
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: ./timemanager-webapp
          push: false
          tags: ghcr.io/swangon/timemanager/timemanager-webapp:latest

  docker-login-and-push:
    name: Log in to GitHub Container Registry and push Docker images
    runs-on: ubuntu-latest
    needs: [build-api, build-webapp]
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Liste des fichiers
        run: ls -la
        
      - name: Push API Image
        uses: docker/build-push-action@v4
        with:
          context: ./timemanager-api
          push: true
          tags: ghcr.io/swangon/timemanager/timemanager-api:latest

      - name: Push Webapp Image
        uses: docker/build-push-action@v4
        with:
          context: ./timemanager-webapp
          push: true
          tags: ghcr.io/swangon/timemanager/timemanager-webapp:latest

  deploy-to-render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: docker-login-and-push
    steps:
      - name: Trigger API Deploy on Render
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          ${{ secrets.RENDER_DEPLOY_HOOK_API }}

      - name: Trigger Webapp Deploy on Render
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          ${{ secrets.RENDER_DEPLOY_HOOK_WEBAPP }}
