name: CI/CD

on:
  push:
    branches: [ 17-finishing-cicd ]
  pull_request:
    branches: [ 17-finishing-cicd ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14'
        otp-version: '24.3'
    
    - name: Install dependencies
      run: |
        cd timemanager-api
        mix deps.get
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install frontend dependencies
      run: |
        cd timemanager-webapp
        npm ci
    

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/17-finishing-cicd'
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and push Docker images
      run: |
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
        docker compose build
        docker compose push
    
    - name: Deploy to server
      env:
        HOST: ${{ secrets.PROD_SERVER_HOST }}
        USERNAME: ${{ secrets.PROD_SERVER_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.PROD_SERVER_SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key docker-compose.yml $USERNAME@$HOST:~/
        ssh -i private_key $USERNAME@$HOST "docker-compose pull && docker-compose up -d"
