name: CI/CD

on:
  push:
    branches: [ 17-finishing-cicd ]
  pull_request:
    branches: [ 17-finishing-cicd ]

permissions:
  contents: write
  packages: write

jobs:
  build-api:
    name: Build and push API
    runs-on: ubuntu-latest
    outputs:
      backend-image: ${{ steps.build-image.outputs.image }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image for API
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: timemanager-api
          push: true
          tags: ghcr.io/swangon/timemanager/timemanager-api:latest

  build-webapp:
    name: Build and push Webapp
    runs-on: ubuntu-latest
    outputs:
      frontend-image: ${{ steps.build-image.outputs.image }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image for Webapp
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: timemanager-webapp
          push: true
          tags: ghcr.io/swangon/timemanager/timemanager-webapp:latest

  deploy-to-render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [build-api, build-webapp]
    steps:
      - name: Trigger API Deploy on Render
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          ${{ secrets.RENDER_DEPLOY_HOOK_API }}

      - name: Trigger Webapp Deploy on Render
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          ${{ secrets.RENDER_DEPLOY_HOOK_WEBAPP }}
